version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
  npm:
    image: node:18.12.1
    working_dir: /app
    entrypoint: ["npm"]
    volumes:
      - ./:/app
  npx:
    image: node:18.12.1
    working_dir: /app
    entrypoint: ["npx"]
    volumes:
      - ./frontend:/app/frontend